<?php
/**
 * Loan Tracking System - WordPress-Style Installer
 * This script sets up the database and creates config.php automatically.
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$config_file = 'config.php';
$schema_file = '../schema.sql'; // Path to schema.sql relative to /api/

// If already installed, prevent access (optional, but safer)
if (file_exists($config_file)) {
    // Check if it's already configured
    include $config_file;
    if (isset($host) && !empty($host)) {
        $already_installed = true;
    }
}

$step = isset($_POST['step']) ? (int)$_POST['step'] : 1;
$error = '';
$success_msg = '';

if ($step == 2 && isset($_POST['install'])) {
    $db_host = $_POST['db_host'];
    $db_name = $_POST['db_name'];
    $db_user = $_POST['db_user'];
    $db_pass = $_POST['db_pass'];

    try {
        // 1. Test Connection
        $pdo = new PDO("mysql:host=$db_host", $db_user, $db_pass);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // 2. Create Database if not exists (might fail on some shared hosts, so we wrap it)
        try {
            $pdo->exec("CREATE DATABASE IF NOT EXISTS `$db_name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        } catch (Exception $e) {
            // Ignore if already exists or no permission to create
        }

        // 3. Select Database
        $pdo->exec("USE `$db_name`;"); 
        
        // 4. Run Schema
        if (file_exists($schema_file)) {
            $sql = file_get_contents($schema_file);
            // Remove 'CREATE DATABASE' and 'USE' lines from schema to avoid conflicts with our UI-defined name
            $sql = preg_replace('/CREATE DATABASE IF NOT EXISTS.*;/i', '', $sql);
            $sql = preg_replace('/USE loan_tracking_db;/i', "USE `$db_name`;", $sql);
            
            $pdo->exec($sql);
        } else {
            throw new Exception("ไม่พบไฟล์ schema.sql กรุณาอัปโหลดไฟล์ให้ครบถ้วน");
        }

        // 5. Generate config.php
        $config_content = "<?php
// Database Configuration - Generated by Installer
\$host = '$db_host';
\$db_name = '$db_name';
\$username = '$db_user';
\$password = '$db_pass';

try {
    \$conn = new PDO(\"mysql:host=\$host;dbname=\$db_name\", \$username, \$password);
    \$conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    \$conn->exec(\"set names utf8\");
} catch(PDOException \$exception) {
    echo json_encode([\"message\" => \"Connection error: \" . \$exception->getMessage()]);
    exit();
}

// CORS Headers
header(\"Access-Control-Allow-Origin: *\");
header(\"Content-Type: application/json; charset=UTF-8\");
header(\"Access-Control-Allow-Methods: POST, GET, PUT, DELETE, OPTIONS\");
header(\"Access-Control-Max-Age: 3600\");
header(\"Access-Control-Allow-Headers: Content-Type, Access-Control-Allow-Headers, Authorization, X-Requested-With\");

if (\$_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    exit();
}
?>";
        if (file_put_contents($config_file, $config_content)) {
            $step = 3;
            $success_msg = "ติดตั้งสำเร็จ! ระบบได้สร้างไฟล์ config.php และฐานข้อมูลเรียบร้อยแล้ว";
        } else {
            throw new Exception("ไม่สามารถสร้างไฟล์ config.php ได้ กรุณาตรวจสอบสิทธิ์การเขียนไฟล์ (Permission)");
        }

    } catch (PDOException $e) {
        $error = "การเชื่อมต่อล้มเหลว: " . $e->getMessage();
    } catch (Exception $e) {
        $error = "เกิดข้อผิดพลาด: " . $e->getMessage();
    }
}

?>
<!DOCTYPE html>
<html lang="th">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ติดตั้งระบบ Loan Tracking 🌳</title>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;700;900&family=Sarabun:wght@400;700&display=swap" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        body { font-family: 'Outfit', 'Sarabun', sans-serif; }
        .forest-gradient { background: linear-gradient(135deg, #065f46 0%, #064e3b 100%); }
    </style>
</head>
<body class="bg-gray-50 min-h-screen flex items-center justify-center p-4">

    <div class="max-w-xl w-full bg-white rounded-[2.5rem] shadow-2xl overflow-hidden">
        <!-- Header -->
        <div class="forest-gradient p-10 text-white text-center relative">
            <div class="absolute top-4 right-4 opacity-10">
                <svg width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 2v20M2 12h20"/></svg>
            </div>
            <h1 class="text-4xl font-black mb-2 tracking-tight">Loan Tracker 🌳</h1>
            <p class="text-emerald-100 font-bold opacity-80 uppercase text-xs tracking-widest">ระบบติดตั้งอัตโนมัติ (Installer)</p>
        </div>

        <div class="p-10">
            <?php if (isset($already_installed)): ?>
                <div class="bg-blue-50 border-2 border-blue-100 p-8 rounded-3xl text-center">
                    <p class="text-blue-600 font-black text-xl mb-4">📍 ระบบดูเหมือนจะติดตั้งไว้แล้ว</p>
                    <p class="text-gray-500 mb-6">หากต้องการติดตั้งใหม่ กรุณาลบไฟล์ <code>api/config.php</code> ออกก่อนครับ</p>
                    <a href="../" class="inline-block bg-slate-900 text-white px-8 py-4 rounded-2xl font-black transition-transform hover:-translate-y-1">ไปที่หน้าแรก</a>
                </div>
            <?php elseif ($step == 1): ?>
                <div class="space-y-8">
                    <div class="text-center">
                        <h2 class="text-2xl font-black text-gray-800">ยินดีต้อนรับ! 👋</h2>
                        <p class="text-gray-400 font-bold mt-2">กรุณาเตรียมข้อมูลฐานข้อมูล SQL ของคุณให้พร้อม</p>
                    </div>
                    
                    <div class="grid grid-cols-1 gap-4 text-sm">
                        <div class="p-4 bg-gray-50 rounded-2xl flex items-center gap-4">
                            <span class="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center font-black">1</span>
                            <span class="text-gray-600 font-bold">ชื่อโฮสต์ (Host)</span>
                        </div>
                        <div class="p-4 bg-gray-50 rounded-2xl flex items-center gap-4">
                            <span class="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center font-black">2</span>
                            <span class="text-gray-600 font-bold">ชื่อฐานข้อมูล (Database Name)</span>
                        </div>
                        <div class="p-4 bg-gray-50 rounded-2xl flex items-center gap-4">
                            <span class="w-8 h-8 rounded-full bg-emerald-100 text-emerald-600 flex items-center justify-center font-black">3</span>
                            <span class="text-gray-600 font-bold">Username & Password ของ SQL</span>
                        </div>
                    </div>

                    <form method="POST">
                        <input type="hidden" name="step" value="2">
                        <button type="submit" class="w-full forest-gradient text-white py-5 rounded-2xl font-black text-xl shadow-xl hover:shadow-emerald-500/20 transition-all active:scale-95">เริ่มการติดตั้งเลย! 🚀</button>
                    </form>
                </div>

            <?php elseif ($step == 2): ?>
                <form method="POST" class="space-y-6">
                    <input type="hidden" name="step" value="2">
                    <input type="hidden" name="install" value="1">

                    <?php if ($error): ?>
                        <div class="bg-red-50 border-2 border-red-100 p-4 rounded-2xl text-red-600 font-bold text-sm">
                            ⚠️ <?php echo htmlspecialchars($error); ?>
                        </div>
                    <?php endif; ?>

                    <div class="space-y-4">
                        <div class="space-y-1">
                            <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest pl-2">Database Host</label>
                            <input type="text" name="db_host" value="localhost" class="w-full px-5 py-4 rounded-2xl border-2 border-gray-100 focus:border-emerald-500 outline-none font-bold" required>
                        </div>
                        <div class="space-y-1">
                            <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest pl-2">Database Name</label>
                            <input type="text" name="db_name" placeholder="loan_tracking_db" class="w-full px-5 py-4 rounded-2xl border-2 border-gray-100 focus:border-emerald-500 outline-none font-bold" required>
                        </div>
                        <div class="grid grid-cols-2 gap-4">
                            <div class="space-y-1">
                                <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest pl-2">Username</label>
                                <input type="text" name="db_user" placeholder="root" class="w-full px-5 py-4 rounded-2xl border-2 border-gray-100 focus:border-emerald-500 outline-none font-bold" required>
                            </div>
                            <div class="space-y-1">
                                <label class="text-[10px] font-black text-gray-400 uppercase tracking-widest pl-2">Password</label>
                                <input type="password" name="db_pass" placeholder="••••••••" class="w-full px-5 py-4 rounded-2xl border-2 border-gray-100 focus:border-emerald-500 outline-none font-bold">
                            </div>
                        </div>
                    </div>

                    <button type="submit" class="w-full forest-gradient text-white py-5 rounded-2xl font-black text-xl shadow-xl hover:shadow-emerald-500/20 transition-all active:scale-95">เชื่อมต่อและติดตั้ง ⚡</button>
                    <p class="text-center text-xs text-gray-400 font-bold">ระบบจะทำการตรวจสอบการเชื่อมต่อและสร้างตารางข้อมูลให้อัตโนมัติ</p>
                </form>

            <?php elseif ($step == 3): ?>
                <div class="text-center space-y-8 animate-in fade-in zoom-in-95 duration-500">
                    <div class="w-24 h-24 bg-emerald-100 rounded-full flex items-center justify-center mx-auto text-emerald-600">
                        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"><path d="M20 6L9 17l-5-5"/></svg>
                    </div>
                    <div class="space-y-2">
                        <h2 class="text-3xl font-black text-gray-800">ติดตั้งสำเร็จ! 🌳🎉</h2>
                        <p class="text-gray-500 font-bold"><?php echo $success_msg; ?></p>
                    </div>

                    <div class="bg-amber-50 border-2 border-amber-100 p-6 rounded-[2rem]">
                        <p class="text-amber-700 font-black text-sm mb-2">⚠️ คำแนะนำด้านความปลอดภัย</p>
                        <p class="text-amber-600/80 text-xs font-bold leading-relaxed">กรุณาลบไฟล์ <strong>api/install.php</strong> ทิ้งทันทีเพื่อป้องกันไม่ให้ผู้อื่นมาติดตั้งทับข้อมูลเดิมของคุณครับ</p>
                    </div>

                    <a href="../" class="block w-full bg-slate-900 text-white py-5 rounded-2xl font-black text-xl shadow-xl transition-transform hover:-translate-y-1">เข้าสู่ระบบจัดการ 🏠</a>
                </div>
            <?php endif; ?>
        </div>
    </div>

</body>
</html>
